apiVersion: v1
kind: Service
metadata:
  name: taiga-frontend
  namespace: taiga
  labels:
    app: taiga
    role: frontend
spec:
  ports:
  - name: frontend
    port: 80
  selector:
    app: taiga
    role: frontend
