apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: taiga-media
  namespace: taiga
  labels:
    app: taiga
    role: public
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
      role: public
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taiga
        role: public
        version: v1
    spec:
      containers:
      - name: taiga-media
        image: jrelva/nginx-autoindex
        ports:
        - containerPort: 80
          name: taiga-media
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/media
          name: taiga-media
          readOnly: true
      volumes:
      - name: taiga-media
        nfs:
          server: '{{nfs_server}}'
          path: '{{nfs_prefix}}/taiga-media'
