apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.223.116
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: console
      port: 8080
  selector:
    app: traefik