apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
    version: v1
data:
  traefik.toml: |-
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
            CertFile = "/acme/server.crt"
            KeyFile = "/acme/server.key"
    [kubernetes]
    [acme]
    email = {{traefik_email}}
    storage = "/acme/acme.json"
    entryPoint = "https"
    onDemand = false
    OnHostRule = true
    [[acme.domains]]
    main = {{traefik_cloud_domain}}
